on:
  schedule:
  - cron:  "*/15 * * * *"
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Read Node.js version to install from `.tool-versions`
        id: fetch-data
        with:
          PERFORMER_DATA_GOOGLE_SHEET_ID: ${{ secrets.PERFORMER_DATA_GOOGLE_SHEET_ID }}
          GOOGLESHEET_API_KEY: ${{ secrets.GOOGLESHEET_API_KEY }}
        uses: tongchen92/hello-world-javascript-action@v1.4
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "data.json"
          json: "${{ steps.fetch-data.outputs.data }}"
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: 'Overwritten by Github Actions - ${date}'